### ISSUE TITLE
Create a compilation for `aarch64-linux`

### ISSUE THREAD

**Issue by heaveless** [chipsenkbeil/distant#234]
Could you create a compilation for `aarch64-linux`?
My idea is to be able to connect to an external server through a tablet using `termux`, I tried to compile it from my own media but I always have the error `aarch64-linux-gnu-gcc command not found archlinux`.

**Comment by chipsenkbeil** [comment]
@heaveless hey there! There's currently #163 open to support termux officially. There are a couple of dependencies that need to be updated for it to compile.

As it turns out, there was already an effort to get a termux build working with some patches, which you can find here: https://github.com/termux/termux-packages/blob/961d5892a375686beb520443df87f8a87bb49ab9/packages/distant/build.sh

**Comment by heaveless** [comment]
@chipsenkbeil Great, I'll check it out now. Thank you :)

**Comment by chipsenkbeil** [comment]
If you need anything else related to termux, feel free to add it to that issue. :)

Closing this out!
