### ISSUE TITLE
Supports for nvim-tree over distant

### ISSUE THREAD

**Issue by allencho1222** [chipsenkbeil/distant#84]
Hi, I'm trying to enhance [_nvim-tree_](https://github.com/kyazdani42/nvim-tree.lua) by using _distant_. Obviously, to fetch file trees of the directory in the remote machine.

I already passed simple test by abstracting file system API (`luv.xxx` and distant API).

However, the problem was:

1. _nvim-tree_ uses **per-file** stat query (e.g., `luv.fs_stat(filepath)`) in the local machine (see [this](https://github.com/kyazdani42/nvim-tree.lua/blob/0a2f6b0b6ba558a88c77a6b262af647760e6eca8/lua/nvim-tree/populate.lua#L13)).
However, this is inefficient in the case of _distant_ because the latency caused by **multiple network transactions (# of files in the directory)** between the local and remote machine.
To solve the problem, _distant_ needs to fetch the metadata of all files in the target directory so that **only one network transaction** happens.

2. _nvim-tree_ requires access permission for each file (e.g., `luv.fs_access(filepath, 'R')`) (see [this](https://github.com/kyazdani42/nvim-tree.lua/blob/0a2f6b0b6ba558a88c77a6b262af647760e6eca8/lua/nvim-tree/populate.lua#L330)). However, _distant_ only fetches whether the file is readonly or not.
I found that in the rust library, functions corresponding to `luv.fs_access(filepath, 'R')` did not exist according to [this page](https://doc.rust-lang.org/std/fs/struct.Permissions.html). However, we might be able to use `mode()` (I'm new to Rust language and I'm not sure). Like 1, we need to do this by **only one network transaction**.

BTW, it seems that this issues is related to [here](https://github.com/chipsenkbeil/distant/issues/63#issue-1028486630). But, instead of batching commands, this issue insists that we need client query to fetch metadata of all files **in the directory**.

**Comment by chipsenkbeil** [comment]
When it comes to batch requests, the distant server supports this already and can be done when using the interactive CLI with JSON. The lua api doesn't offer this at the moment and the open issue is https://github.com/chipsenkbeil/distant/issues/63 for distant and https://github.com/chipsenkbeil/distant.nvim/issues/40 for distant.nvim.

[EDIT] Seems you've beaten me to referring to those issues. :)

The other issue of relevance would be https://github.com/chipsenkbeil/distant/issues/73, where we could support listing a directory and then chaining the results into a series of metadata requests, but that is a lot more work and needs a bit more thought into how it would be handled.

As for permissions themselves, Rust's standard library only exposes permissions that are cross-platform, which at the moment is the readonly flag. Do you know if `fs_access` is only used to check if a file can be read? In Rust, we'd use the unix-only portion of the standard library, [PermissionsExt](https://doc.rust-lang.org/std/os/unix/fs/trait.PermissionsExt.html).

If you're needing to know the read, write, and execute permissions of a file, then that would either need to be a new request/response, augmented to the existing metadata (preferred), or do a hack for now involving submitting a `ProcRun` request to report back the status with something like `ls -l` that you'd have to parse locally.

If we made the data part of a new response (or augment the existing response), the read/write/executable flags would all need to be optional since some systems support that data and others don't.

**Comment by allencho1222** [comment]
Hi, thank you for the comments. 

It seems that I can do what I wanted to do by using the two network-call approach you mentioned.

Could you provide the toy example using CLI so that I can try to expose the API to the lua?

**Comment by chipsenkbeil** [comment]
I've opened up #86 to address the need for unix-specific permissions.

As another heads up, I'm considering switching `distant.nvim` back to using the JSON interactive CLI instead of a shared library. This won't affect the public API that the plugin provides, though. So, nothing that we build on top of the distant.nvim plugin should change in terms of public API compatibility.

**Comment by allencho1222** [comment]
As you mentioned, I tried interactive CLI and saw that batching commands worked.

However, I could not find how to expose such functionality to the lua module.
It seems that shared library uses functions generated by the macro function and it only accepts single command (not `Vec<RequestData>`).
In addition, even though there exist function called `process` that uses `Vec<RequestData>` as one of arguments, it seems that the function call hierarchy from the lua module does not meet `process`.

Are there simple solutions to implement batching commands based on what you mentioned "using the JSON interactive CLI instead of a shared library"?
Does it mean that nvim uses 'distant action -i' ?

**Comment by chipsenkbeil** [comment]
@allencho1222 I've added unix and windows metadata that can be returned, but haven't published a new release yet. I'll need to update the plugin due to some breaking changes, so expect it to be ready in a couple of weeks.

**Comment by chipsenkbeil** [comment]
Closing this issue out due to lack of activity. No warning here as everything needed to do this is now available in the binary and plugin.
